# Generated by Django 5.0.4 on 2024-04-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho', '0002_rename_status_carlist_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='chassisnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
